apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ajuste
  github.com/user-login: ajuste
spec:
  profile:
    displayName: Alvaro Juste
    email: ajuste@zerofox.com
  memberOf: [engineers]