apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: tgunther-zerofox
  github.com/user-login: tgunther-zerofox
spec:
  profile:
    displayName: Tomas Gunther
    email: tgunther@zerofox.com
  memberOf: [engineers]
