app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: https://devportal.zerofox.com
  analytics:
    matomo:
      siteId: 1
      urlBase: https://stats.zerofox.com
      srcUrl: https://cdn.zerofox.com/stats/stats.js

auth:
  environment: prod

ai:
  supportedSources: ['catalog', 'techdocs', 'tech-docs']
  embeddings:
    openai:
      openAIApiKey: ${OPENAI_API_KEY}

backend:
  baseUrl: https://devportal.zerofox.com
  listen:
    port: 7007
    host: 0.0.0.0
  database:
    client: pg
    connection:
      host: ${DB_HOST}
      port: 5432
      user: ${DB_USER}
      password: ${DB_PASSWORD}
  
  auth:
    dangerouslyDisableDefaultAuthPolicy: true
    keys:
     - secret: 'Q@w:;@RUnL#@@&Z'

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: ${TECHDOCS_AWSS3_BUCKET_NAME}

grafana:
  domain: https://grafana-prod.zerofox.com
  unifiedAlerting: true

proxy:
  endpoints:
    '/grafana/api':
      target: https://grafana-prod.zerofox.com
      headers:
        Authorization: Bearer ${GRAFANA_TOKEN}

scorecards:
  jsonDataUrl: /api/zf-insights/s3/prod-backstage/service_assessment/

catalog:
  processingInterval:
    seconds: 3600
    
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Template, Domain]

  locations:
    - type: github-discovery
      target: https://github.com/riskive

qeta:
  allowAnonymous: false
  allowMetadataInput: true
  allowGlobalEdits: false
  entities:
    kinds: ['System']
    max: 3
  tags:
    allowCreation: true
    max: 5
  moderators:
    - group:default/developer-portal-qa-moderators
  storage:
    type: s3
    folder: /qeta-attachments
    bucket: ${BACKEND_BUCKET}
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    sessionToken: ${AWS_SESSION_TOKEN}
    region: us-west-2

scaffolderActions:
  env: ${ENV}
  aws:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    sessionToken: ${AWS_SESSION_TOKEN}
    region: us-west-2
  nomad:
    addr: 'https://nomad-prod.zerofox.com'
    token: ${NOMAD_TOKEN}
  jira:
    proxyPath: /jira/api
    user: ${JIRA_USER}
    password: ${JIRA_PASSWORD}
    addr: zf.atlassian.net

nomad:
  addr: 'https://nomad-prod.zerofox.com'
  token: ${NOMAD_TOKEN}