integrations:
  # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
  # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
      apps:
        - appId: ${GITHUB_APP_ID}
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_APP_SECRET}
          webhookSecret: dummy
          privateKey: ${GITHUB_APP_PRIVATE_KEY}
  
  # for accessing git repositories in Azure DevOps. credential type uses a PAT
  # do NOT use the credential keyword described in the docs: https://backstage.io/docs/integrations/azure/locations/
  azure:
    - host: dev.azure.com
      organizations:
        - idexperts
      token: ${AZURE_TOKEN}

ai:
  supportedSources: ['catalog', 'tech-docs']

scorecards:
  jsonDataUrl: http://localhost:7007/api/zf-insights/s3/qa-backstage/service_assessment/
    
auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_APP_SECRET}
        resolvers:
          - resolver: usernameMatchingUserEntityName
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_APP_SECRET}
        guest:
          dangerouslyAllowOutsideDevelopment: true
      qa:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_APP_SECRET}
        resolvers:
          - resolver: usernameMatchingUserEntityName
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_APP_SECRET}
        guest:
          dangerouslyAllowOutsideDevelopment: true
      prod:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_APP_SECRET}
        resolvers:
          - resolver: usernameMatchingUserEntityName
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_APP_SECRET}
        guest:
          dangerouslyAllowOutsideDevelopment: true

scaffolderActions:
  env: qa
  aws:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    sessionToken: ${AWS_SESSION_TOKEN}
    region: us-west-2
  nomad:
    addr: 'https://nomad-qa.zerofox.com'
    token: ${NOMAD_TOKEN}
  jira:
    proxyPath: /jira/api
    user: ${JIRA_USER}
    password: ${JIRA_PASSWORD}
    addr: zf.atlassian.net

nomad:
  addr: 'https://nomad-qa.zerofox.com'
  token: ${NOMAD_TOKEN}

catalog:
  processingInterval:
    seconds: 3600
    
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Template, Domain]

  locations:
    - type: github-discovery
      target: https://github.com/riskive

    - type: file
      target: ../../data/noowner.yaml

    - type: file
      target: ../../data/templates/service-assessment.yaml

    - type: file
      target: ../../data/templates/onboard-nomad-repo.yaml

    - type: file
      target: ../../data/templates/onboard-library-repo.yaml

    - type: file
      target: ../../data/templates/onboard-generic-repo.yaml

    - type: file
      target: ../../data/templates/standard-doc-generate-for-service.yaml
    
    - type: file
      target: ../../data/templates/data-line-sql-to-bq.yaml

    - type: file
      target: ../../data/templates/onboard-generic-repo.yaml

    - type: file
      target: ../../data/templates/standard-doc-generate-for-generic.yaml

    - type: file
      target: ../../data/templates/standard-doc-generate-for-library.yaml

    - type: url
      target: https://github.com/riskive/storage-services-observability/blob/master/rds-catalog-info.yaml

    - type: url
      target: https://github.com/riskive/go-dm/blob/master/catalog-info.yaml

    - type: url
      target: https://github.com/riskive/ui-architecture/blob/master/catalog-info.yaml

qeta:
  allowAnonymous: false
  allowMetadataInput: true
  allowGlobalEdits: false
  entities:
    kinds: ['System']
    max: 3
  tags:
    allowCreation: true
    max: 5
  moderators:
    - group:default/developer-portal-qa-moderators
  storage:
    type: s3
    folder: /qeta-attachments
    bucket: ${BACKEND_BUCKET}
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    sessionToken: ${AWS_SESSION_TOKEN}
    region: us-west-2

rds:
  db:
    platformdb-prod-b:
      host: platformdb-prod-b.cmtfynbirqqp.us-west-2.rds.amazonaws.com
      port: 3306
      user: ${RDS_MONOLITH_PROD_USER}
      password: ${RDS_MONOLITH_PROD_PASSWORD}
    prod-cs-takedown-api-xx:
      host: prod-cs-takedown-api-02.cmtfynbirqqp.us-west-2.rds.amazonaws.com
      port: 5432
      user: ${RDS_CSTAKEDOWNAPI_PROD_USER}
      password: ${RDS_CSTAKEDOWNAPI_PROD_PASSWORD}
    prod-cs-ma-api:
      host: prod-cs-ma-api.cmtfynbirqqp.us-west-2.rds.amazonaws.com
      port: 5432
      user: ${RDS_CSTMAAPI_PROD_USER}
      password: ${RDS_MAAPI_PROD_PASSWORD}

