app:
  title: Zerofox Dev Portal
  baseUrl: http://localhost:3003
  analytics:
    matomo:
      siteId: 1
      urlBase: https://stats-qa.zerofox.com
      srcUrl: https://cdn-qa.zerofox.com/stats/stats.js
  reporting:
    pillarAdoption:
      excludedRepositories: ${REPORTING_PILLAR_ADOPTION_EXCLUDED_REPOSITORIES}
  experimental:
    packages: all

ai:
  supportedSources: ['catalog', 'techdocs', 'tech-docs']
  embeddings:
    openai:
      openAIApiKey: ${OPENAI_API_KEY}

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    okta:
      development:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: https://zerofox.okta.com
        resolvers:
          - resolver: usernameMatchingUserEntityName
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
          clientId: ${AUTH_OKTA_CLIENT_ID}
          clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
          audience: https://zerofox.okta.com
        guest:
          dangerouslyAllowOutsideDevelopment: true
      qa:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: https://zerofox.okta.com
        resolvers:
          - resolver: usernameMatchingUserEntityName
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
          clientId: ${AUTH_OKTA_CLIENT_ID}
          clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
          audience: https://zerofox.okta.com
        guest:
          dangerouslyAllowOutsideDevelopment: true
      prod:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: https://zerofox.okta.com
        resolvers:
          - resolver: usernameMatchingUserEntityName
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
          clientId: ${AUTH_OKTA_CLIENT_ID}
          clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
          audience: https://zerofox.okta.com
        guest:
          dangerouslyAllowOutsideDevelopment: true

organization:
  name: Zerofox

jira:
  proxyPath: /jira/api
  user: ${JIRA_USER}
  bearer: ${JIRA_TOKEN}
  addr: zf.atlassian.net

grafana:
  domain: https://grafana-qa.zerofox.com

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", '*.zerofox.com']
    script-src: ["'self'", "'unsafe-eval'", '*.zerofox.com']
    img-src: ["'self'", 'data:', '*.zerofox.com', '*.github.com', '*.githubusercontent.com']
    default-src: ["'self'", '*.zerofox.com']

  cors:
    origin: http://localhost:3003
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

  auth:
    dangerouslyDisableDefaultAuthPolicy: true
    keys:
     - secret: ${AUTH_SECRET}

scorecards:
  jsonDataUrl: /api/zf-insights/s3/qa-backstage/service_assessment/

badges:
  bucket: ${BADGES_BUCKET}
  bucket_region: ${BADGES_BUCKET_REGION}

qeta:
  allowAnonymous: false
  allowMetadataInput: true
  allowGlobalEdits: false
  entities:
    kinds: ['System']
    max: 3
  tags:
    allowCreation: true
    max: 5
  moderators:
    - group:default/developer-portal-qa-moderators
  storage:
    type: s3
    folder: /qeta-attachments
    bucket: ${BACKEND_BUCKET}
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    sessionToken: ${AWS_SESSION_TOKEN}
    region: us-west-2

integrations:
  # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
  # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
      apps:
        - appId: ${GITHUB_APP_ID}
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_APP_SECRET}
          webhookSecret: dummy
          privateKey: ${GITHUB_APP_PRIVATE_KEY}

  # for accessing git repositories in Azure DevOps. credential type uses a PAT
  # do NOT use the credential keyword described in the docs: https://backstage.io/docs/integrations/azure/locations/
  azure:
    - host: dev.azure.com
      organizations:
        - idexperts
      token: ${AZURE_TOKEN}

proxy:
  endpoints:
    '/jira/api':
      target: https://zf.atlassian.net
      headers:
        Authorization:
          $env: JIRA_TOKEN
        Accept: 'application/json'
        Content-Type: 'application/json'
        X-Atlassian-Token: 'no-check'
        User-Agent: "AnyRandomString"
    '/grafana/api':
      target: https://grafana-qa.zerofox.com
      headers:
        Authorization: Bearer ${GRAFANA_TOKEN}

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

scaffolderActions:
  env: ${ENV}
  aws:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    sessionToken: ${AWS_SESSION_TOKEN}
    region: us-west-2
  nomad:
    addr: 'https://nomad-qa.zerofox.com'
    token: ${NOMAD_TOKEN}
  jira:
    proxyPath: /jira/api
    user: ${JIRA_USER}
    bearer: ${JIRA_TOKEN}
    addr: zf.atlassian.net

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  sessionToken: ${AWS_SESSION_TOKEN}
  region: us-west-2

techInsights:
  factRetrievers:
    entityOwnershipFactRetriever:
      cadence: '0 1 * * *'
      lifecycle: { timeToLive: { weeks: 2 } }
    entityMetadataFactRetriever:
      cadence: '0 1 * * *'
      lifecycle: { timeToLive: { weeks: 2 } }
    techdocsFactRetriever:
      cadence: '0 3 * * *'
      lifecycle: { timeToLive: { weeks: 2 } }
    githubFactRetriever:
      cadence: '0 0/4 * * *'
      lifecycle: { timeToLive: { weeks: 2 } }
      timeout:
        hours: 2
    ownershipFactRetriever:
      cadence: '0 * * * *'
      lifecycle: { timeToLive: { weeks: 2 } }
      timeout:
        hours: 2

nomad:
  addr: 'https://nomad-qa.zerofox.com'
  token: ${NOMAD_TOKEN}

catalog:
  processingInterval:
    seconds: 3600

  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Template, Domain]

  locations:
    - type: github-discovery
      target: https://github.com/riskive

    - type: file
      target: ./data/noowner.yaml

    - type: file
      target: ./data/templates/service-assessment.yaml

    - type: file
      target: ./data/templates/onboard-nomad-repo.yaml

    - type: file
      target: ./data/templates/onboard-library-repo.yaml

    - type: file
      target: ./data/templates/onboard-generic-repo.yaml

    - type: file
      target: ./data/templates/data-ingestion-sql-to-bq.yaml

    - type: file
      target: ./data/templates/standard-doc-generate-for-service.yaml

    - type: file
      target: ./data/templates/standard-doc-generate-for-generic.yaml

    - type: file
      target: ./data/templates/standard-doc-generate-for-library.yaml

    - type: file
      target: ./data/templates/data-ingestion-sql-to-bq.yaml

codeCoverage:
  bodySizeLimit: 5mb # Defaults to 100kb, see https://www.npmjs.com/package/body-parser#limit
