# auth:
#   environment: production
#   providers:
#     github:
#       development:
#         clientId: ${AUTH_GITHUB_CLIENT_ID}
#         clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: https://devportal.zerofox.com

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: https://devportal.zerofox.com
  listen:
    port: 7007
    # The following host directive binds to all IPv4 interfaces when its value
    # is "0.0.0.0". This is the most permissive setting. The right value depends
    # on your specific deployment. If you remove the host line entirely, the
    # backend will bind on the interface that corresponds to the backend.baseUrl
    # hostname.
    host: 0.0.0.0
  database:
    client: better-sqlite3
    connection: ":memory:"
  cache:
    store: memory

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'awsS3'

    awsS3:
      bucketName: ${TECHDOCS_AWSS3_BUCKET_NAME}

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Template, Domain]

  locations:
    - type: file
      target: ./examples/roles.yaml
      rules:
        - allow: [Group]

    - type: file
      target: ./examples/teams.yaml
      rules:
        - allow: [Group]
        
    - type: file
      target: ./examples/users.yaml
      rules:
        - allow: [User]
        
    - type: file
      target: ./examples/domains.yaml
      rules:
        - allow: [Domain]

    # headless-browser
    - type: url
      target: https://github.com/ajuste/backstage-poc-config/blob/main/headless-browser/.backstage/backstage.yaml

    # headless-browser-analysis
    - type: url
      target: https://github.com/ajuste/backstage-poc-config/blob/main/headless-browser-analysis/.backstage/backstage.yaml

    # zf-api
    - type: url
      target: https://github.com/ajuste/API/blob/backstage/backstage.yaml
      rules:
        - allow: [Component, API, Group, System]

    # intel-api
    - type: url
      target: https://github.com/ajuste/intel-api/blob/backstage/backstage.yaml
      rules:
        - allow: [Component, API, Group, System]

    # intel-backend
    - type: url
      target: https://github.com/ajuste/intel-backend/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # acs
    - type: url
      target: https://github.com/ajuste/alert-content-service/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # search-engine
    - type: url
      target: https://github.com/ajuste/search-engine/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # scrapy
    - type: url
      target: https://github.com/ajuste/scrapy/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # alert-creator
    - type: url
      target: https://github.com/ajuste/alert-creator/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # rule-engine
    - type: url
      target: https://github.com/ajuste/rule-engine/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # ml-enricher
    - type: url
      target: https://github.com/ajuste/ml-enricher/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # ml-enricher
    - type: url
      target: https://github.com/ajuste/DC/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # go-dm
    - type: url
      target: https://github.com/ajuste/go-dm/blob/backstage/backstage.yaml

    # form-detection
    - type: url
      target: https://github.com/ajuste/form-detection/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # email-analysis
    - type: url
      target: https://github.com/ajuste/email-analysis/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # go-twitter
    - type: url
      target: https://github.com/ajuste/go-twitter/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # zf-twitter
    - type: url
      target: https://github.com/ajuste/zf-twitter/blob/master/catalog-info.yaml
      rules:

    # ocr-analysis
    - type: url
      target: https://github.com/ajuste/ocr-analysis/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # cve-api
    - type: url
      target: https://github.com/ajuste/cve-api/blob/apidocs_poc/backstage.yaml
      rules:
        - allow: [Component, API, Group, System]

    # ecr
    - type: url
      target: https://github.com/ajuste/entity-content-locker/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]

    # onboarding
    - type: url
      target: https://github.com/ajuste/onboarding-tldr-engineers/blob/master/catalog-info.yaml
      rules:
        - allow: [Component]

    # laptop setup
    - type: url
      target: https://github.com/ajuste/zfe-100-laptop-setup/blob/master/catalog-info.yaml
      rules:
        - allow: [Component]

    # architecture
    - type: url
      target: https://github.com/ajuste/architecture/blob/master/catalog-info.yaml

    # templates
    - type: url
      target: https://github.com/ajuste/backstage-poc-config/blob/main/form-detection/.backstage/templates.yaml
      rules:
        - allow: [Template]
      
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml
      rules:
        - allow: [Template]
    
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/create-react-app/template.yaml
      rules:
        - allow: [Template]

  # # config options: https://node-postgres.com/api/client
  # database:
  #   client: pg
  #   connection:
  #     host: ${DB_HOST}
  #     port: ${DB_PORT}
  #     user: ${DB_USER}
  #     password: ${DB_PASSWORD}
  #     # https://node-postgres.com/features/ssl
  #     # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
  #     # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
  #     # ssl:
  #     #   ca: # if you have a CA file and want to verify it you can uncomment this section
  #     #     $file: <file-path>/ca/server.crt
