# auth:
#   environment: production
#   providers:
#     github:
#       development:
#         clientId: ${AUTH_GITHUB_CLIENT_ID}
#         clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: https://devportal.zerofox.com

backend:
  baseUrl: https://devportal.zerofox.com
  listen:
    port: 7007
    host: 0.0.0.0
  database:
    client: pg
    connection:
      host: ${DB_HOST}
      port: 5432
      user: ${DB_USER}
      password: ${DB_PASSWORD}
  cache:
    store: memory

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'awsS3'

    awsS3:
      bucketName: ${TECHDOCS_AWSS3_BUCKET_NAME}

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Template, Domain]

  locations:
    
    - type: file
      target: ./examples/roles.yaml
      rules:
        - allow: [Group]

    - type: file
      target: ./examples/teams.yaml
      rules:
        - allow: [Group]
        
    - type: file
      target: ./examples/users.yaml
      rules:
        - allow: [User]

    # cs-takedown-api
    - type: url
      target: https://github.com/riskive/cs-takedown-api/blob/master/catalog-info.yaml
      rules:
        - allow: [Component, API, Group, System]