apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    name: backstage
    description: Centralized platform providing resources like documentation, APIs, code samples, and tools to support and streamline software development
    annotations:
        backstage.io/code-coverage: enabled
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: riskive/backstage
        zerofox.com/pillar: Sustaining
    links:
        - url: https://nomad-qa.zerofox.com/ui/jobs/backstage
          title: Nomad QA
        - url: https://nomad-stag.zerofox.com/ui/jobs/backstage
          title: Nomad Stag
        - url: https://nomad-prod.zerofox.com/ui/jobs/backstage
          title: Nomad Prod
spec:
    owner: noowner
    lifecycle: production
    children: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: backend
    description: Component that servces both frontend and backend for Backstage.
    annotations:
        zerofox.com/pillar: Sustaining
    namespace: backstage
    links:
        - url: https://nomad-qa.zerofox.com/ui/jobs/backstage/backend
          title: Nomad QA
        - url: https://nomad-stag.zerofox.com/ui/jobs/backstage/backend
          title: Nomad Stag
        - url: https://nomad-prod.zerofox.com/ui/jobs/backstage/backend
          title: Nomad Prod
spec:
    owner: backstage/owner
    lifecycle: production
    type: service
    system: default/backstage
    children: []
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
    name: backstage-templates
    annotations:
        zerofox.com/pillar: Sustaining
spec:
    lifecycle: production
    type: url
    system: default/backstage
    children: []
    targets:
        - ./data/templates/onboard-library-repo.yaml
        - ./data/templates/onboard-nomad-repo.yaml
        - ./data/templates/service-assessment.yaml
        - ./data/templates/standard-doc-generate-for-service.yaml
        - ./data/templates/onboard-generic-repo.yaml
        - ./data/templates/standard-doc-generate-for-generic.yaml
        - ./data/templates/standard-doc-generate-for-library.yaml
