apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: devportal
    description: Backstage devportal
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: backstage/backstage
        zerofox.com/pillar: Other
spec:
    owner: ajuste
    lifecycle: experimental
    type: website
    children: []
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: service-assessment-template
spec:
  type: url
  targets:
    - https://github.com/riskive/backstage/blob/master/data/templates/service-assessment.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: no-owner
spec:
  type: url
  targets:
    - https://github.com/riskive/backstage/blob/master/data/templates/no-owner.yaml