version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LOCAL_DEV: 'true'
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    image: backstage:latest

  db:
    environment:
      POSTGRES_USER: backstage
      POSTGRES_DB: backstage
      PGDATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:14
    command: ['postgres']
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  local:
    image: backstage:latest
    command: yarn dev
    depends_on:
      - db
      - base
    ports:
      - '7007:7007'
      - '3003:3003'
    stdin_open: true
    tty: true
    environment:
      APP_CONFIG_backend_database_client: pg
      APP_CONFIG_backend_database_connection_host: db
      APP_CONFIG_backend_database_connection_port: 5432
      APP_CONFIG_backend_database_connection_user: backstage
    env_file:
      - .env
    restart: always
    volumes:
       - .:/app
volumes:
  db_data:
    driver: local
