site_name: backstage documentation
repo_url: https://github.com/riskive/backstage/
nav:
    - Home: README.md
    - Contributing: CONTRIBUTING.md
    - Running locally playbook: playbook-running_locally.md
    - Writing tests playbook: playbook-writing_tests.md
    - Creating plugins playbook: playbook-creating_plugins.md
    - Generating an Azure DevOps PAT playbook: playbook-generating-azure-pat.md
    - Deleting entities playbook: playbook-moving_deleting_entities.md
    - Release+Deploy: RELEASE+DEPLOY.md
    - Testing: TESTING.md
plugins:
    - techdocs-core
